# Array Pair Sum

## Problem

Given an integer array, output all the ** *unique* ** pairs that sum up to a specific value **k**.

So the input:
    
    pair_sum([1,3,2,2],4)

would return **2** pairs:

     (1,3)
     (2,2)

**NOTE: FOR TESTING PURPOSES CHANGE YOUR FUNCTION SO IT OUTPUTS THE NUMBER OF PAIRS**

## Solution

Fill out your solution below:

In [4]:
def pair_sum(arr,k):
    seen=set()
    num_pair=0
    pairs=[]
    for i in arr:
        if k-i in seen:
            num_pair+=1
            pairs.append((i,k-i))
        else:
            seen.add(i)
    return num_pair

In [2]:
pair_sum([1,3,2,2],4)

(2, [(3, 1), (2, 2)])

# Test Your Solution

In [5]:
"""
RUN THIS CELL TO TEST YOUR SOLUTION
"""
from nose.tools import assert_equal

class TestPair(object):
    
    def test(self,sol):
        assert_equal(sol([1,9,2,8,3,7,4,6,5,5,13,14,11,13,-1],10),6)
        assert_equal(sol([1,2,3,1],3),1)
        assert_equal(sol([1,3,2,2],4),2)
        print 'ALL TEST CASES PASSED'
        
#Run tests
t = TestPair()
t.test(pair_sum)
    

ALL TEST CASES PASSED


## Good Job!

Given a matrix of integers and coordinates of a rectangular region within the matrix, find the sum of numbers falling inside the rectangle.

In [15]:
import numpy as np
mat=np.random.rand(4,4)
print mat
print mat[0,1],mat[2,3]

[[ 0.34446936  0.62740996  0.2396558   0.30283486]
 [ 0.97533633  0.83149991  0.19832194  0.92809584]
 [ 0.16074509  0.99496621  0.15442192  0.67987989]
 [ 0.6388417   0.13907701  0.10360133  0.5668586 ]]
0.627409964272 0.679879888428


In [12]:
#input: coordinates of diagnals, A,D

def matrixRegionSum1(matrix, A, D):
    sum=matrix[]

0.80358128927653949