# Array Pair Sum + matrix sum

## Problem

Given an integer array, output all the ** *unique* ** pairs that sum up to a specific value **k**.

So the input:
    
    pair_sum([1,3,2,2],4)

would return **2** pairs:

     (1,3)
     (2,2)

**NOTE: FOR TESTING PURPOSES CHANGE YOUR FUNCTION SO IT OUTPUTS THE NUMBER OF PAIRS**

## Solution

Fill out your solution below:

In [4]:
def pair_sum(arr,k):
    seen=set()
    num_pair=0
    pairs=[]
    for i in arr:
        if k-i in seen:
            num_pair+=1
            pairs.append((i,k-i))
        else:
            seen.add(i)
    return num_pair

In [2]:
pair_sum([1,3,2,2],4)

(2, [(3, 1), (2, 2)])

# Test Your Solution

In [5]:
"""
RUN THIS CELL TO TEST YOUR SOLUTION
"""
from nose.tools import assert_equal

class TestPair(object):
    
    def test(self,sol):
        assert_equal(sol([1,9,2,8,3,7,4,6,5,5,13,14,11,13,-1],10),6)
        assert_equal(sol([1,2,3,1],3),1)
        assert_equal(sol([1,3,2,2],4),2)
        print 'ALL TEST CASES PASSED'
        
#Run tests
t = TestPair()
t.test(pair_sum)
    

ALL TEST CASES PASSED


## Matrix Sum from Arden Dertat

Given a matrix of integers and coordinates of a rectangular region within the matrix, find the sum of numbers falling inside the rectangle.

In [11]:
import numpy as np
mat=np.random.randint(5, size=(4, 4))
print mat
print mat[0,0],mat[2,3]

[[4 2 2 3]
 [1 4 2 3]
 [0 4 0 3]
 [3 2 0 4]]
4 3


In [9]:
#input: coordinates of diagnals, A,D

def matrixRegionSum1(matrix, A, D):
    sum=0
    for i in range(A[0],D[0]+1):
        for j in range(A[1],D[1]+1):
            sum+=matrix[i][j]
    return sum
            

In [13]:
matrixRegionSum1(mat,[0,0],[2,3])

28

# python fibonacci DP recap

In [18]:
#basic recursive

def fib(n):
    if n<=2:
        return 1
    else:
        return fib(n-1)+fib(n-2)

In [21]:
fib(6)

8

In [ ]:
#0,1,1,2,3,5,8,

## efficient solution by precomputation

In [ ]:
def precomputeSums(matrix):
    topRow, bottomRow=(0, len(matrix)-1)
    leftCol, rightCol=(0, len(matrix[0])-1)
    sums=[[0]*(rightCol-leftCol+1) for i in range(bottomRow-topRow+1)]
    sums[topRow][leftCol]=matrix[topRow][leftCol]
 
    for col in range(leftCol+1, rightCol+1):
        sums[topRow][col]=sums[topRow][col-1]+matrix[topRow][col]
    for row in range(topRow+1, bottomRow+1):
        sums[row][leftCol]=sums[row-1][leftCol]+matrix[row][leftCol]
 
    for col in range(leftCol+1, rightCol+1):
        columnSum=matrix[topRow][col]
        for row in range(topRow+1, bottomRow+1):
            sums[row][col]=sums[row][col-1]+matrix[row][col]+columnSum
            columnSum+=matrix[row][col]
 
    return sums

In [14]:
matrix=mat
topRow, bottomRow=(0, len(matrix)-1)
leftCol, rightCol=(0, len(matrix[0])-1)
sums=[[0]*(rightCol-leftCol+1) for i in range(bottomRow-topRow+1)]

In [17]:
sums

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]